### ISSUE TITLE
Search button doesn't work in Installed view

### ISSUE THREAD

**Issue by jbicha** [system76/pop-shop#13]
Pop!_OS 17.10 Beta (build 27)

In the Updates panel or when looking at a spec, the Search button can't be selected.

Suggestion: maybe it would be better if the search button would disappear if it's unusable in a particular mode.

**Comment by cassidyjames** [comment]
This is actually a theme bug filed at https://github.com/system76/pop-gtk-theme/issues/34

The search is in fact insensitive, but it's difficult to tell.

**Comment by jbicha** [comment]
Ok, but why is it insensitive? More specifically:

- Why does search not work there?
- Why is it better to show an insensitive button than just hiding the button?

**Comment by cassidyjames** [comment]
1. I believe because it would not be clear which context you're searching. Are you filtering the updates view? Are you searching whichever last view you were in? Are you searching all apps? I think it'd make sense to re-enable it if/when we add filtering to the updates view.

2. Good Design:tm: :wink: When there is an interface element that can be used in certain contexts, it's typically less jarring to mark it as insensitive when it's unusable than to always hide and show things. From [the elementary HIG](https://elementary.io/docs/human-interface-guidelines#widget-concepts):
    > It's usually better to make a widget insensitive than to hide it altogether. Making a widget insensitive informs the user that the functionality is available, but only after a certain condition is met. Hiding the widget gives the impression that the functionality is not available at all or can leave a user wondering why a feature has suddenly "disappeared".

**Comment by cassidyjames** [comment]
@jbicha fwiw I've also filed a feature request to search/filter the updates view upstream at https://github.com/elementary/appcenter/issues/493 as a result of this discussion

**Comment by jbicha** [comment]
My initial thinking is that "Controls That Do Nothing" and "Hidden Widgets" are more relevant here.

There is nothing the user can do and there is nothing their computer is missing for that feature to not work because that feature is not implemented at all there.

**Comment by BarbzYHOOL** [comment]
can someone reopen this since it has never been fixed?
